[world]
name = "Moon Bag Vibes"
description = "The cosmic-themed push-your-luck rogue-like bag-building game where players draw orbs from a bag to score points while avoiding bombs. Will you risk it for moon rocks, or will you just kick rocks?"
seed = "dojo_intro"

[namespace]
default = "di"

[env]
rpc_url = "https://api.cartridge.gg/x/moonbagvibes/katana"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
world_address = "0x04d9778a74d2c9e6e7e4a24cbe913998a80de217c66ee173a604d06dea5469c3"

[writers]
"di" = ["di-actions"]
